// <auto-generated />
namespace ELearning.Infrasturcture.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class InitUsersTables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitUsersTables));
        
        string IMigrationMetadata.Id
        {
            get { return "202207250907002_Init UsersTables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
